language: r

r:
#  - oldrel
  - release
#  - devel
 
 cache:
  - packages
  - ccache

latex: false

pandoc: false

addons:
  apt:
    packages:
      - libudunits2-dev

#r_packages:
#  - covr

#after_success:
#  - Rscript -e 'library(covr); codecov()'
