language: r

r:
#  - oldrel
  - release
#  - devel
 
cache:
  - packages
  - ccache

latex: false

pandoc: false

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgeos-dev
      - libgdal-dev

r_packages:
  - sf
#  - covr

#after_success:
#  - Rscript -e 'library(covr); codecov()'
