language: r

r:
  - oldrel
  - release
  - devel

# blocklist
branches:
  except:
    - develop

# safelist
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # matches versioning... including tags

cache:
  - packages
  - ccache

latex: false

dist: bionic
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libgeos-dev
      - libgdal-dev

r_packages:
  - covr
#  - sf

after_success:
  - Rscript -e 'library(covr); codecov()'
